### ISSUE TITLE
org.bluez.Error.Failed', 'le-connection-abort-by-local'

### ISSUE THREAD

**Issue by diogodh** [regevbr/RaspiNukiBridge#10]
Add-on version: 0.0.23
You are running the latest version of this add-on.
System: Home Assistant OS 9.4  (aarch64 / raspberrypi3-64)
Home Assistant Core: 2023.1.0
Home Assistant Supervisor: 2022.12.1

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2023-01-05 16:48:31.409|I|config.py:144|Access Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2023-01-05 16:48:31.410|I|config.py:145|app_id: xxxxxxxxxxxxxxxxxxxxx
2023-01-05 16:48:31.414|I|config.py:150|Generating new keys
2023-01-05 16:48:31.416|I|config.py:154|bridge_public_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2023-01-05 16:48:31.417|I|config.py:155|bridge_private_key: xxxxxxxxxxxxxxxxxxxxxxxxxxx
2023-01-05 16:48:34.486|I|nuki.py:254|Waiting for more tasks with timeout
2023-01-05 16:48:34.488|I|nuki.py:676|Nuki connecting
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Nuki.pair() done, defined at /opt/./nuki.py:744> exception=BleakDBusError('org.bluez.Error.Failed', 'le-connection-abort-by-local')>
Traceback (most recent call last):
  File "/opt/./nuki.py", line 749, in pair
    await self.connect()
  File "/opt/./nuki.py", line 677, in connect
    await self._client.connect()
  File "/usr/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 278, in connect
    assert_reply(reply)
  File "/usr/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] le-connection-abort-by-local

**Comment by diogodh** [comment]
Suddenly it worked. No idea why.

**Comment by Hely0n** [comment]
I have this problem too. Can you give some tips what you have done until it worked?
