### ISSUE TITLE
paring not possible

### ISSUE THREAD

**Issue by HPWicked** [regevbr/RaspiNukiBridge#13]
Hey I am getting the same error message again and again: Unfortunately, I cannot connect with the Smart Look 3.0 w/o the bridge. Please help me :D 

```
Add-on version: 0.0.23
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.2.1
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2023-02-04 22:05:20.886|I|config.py:144|Access Token: -deleted-
2023-02-04 22:05:20.887|I|config.py:145|app_id: -deleted-
2023-02-04 22:05:20.888|I|config.py:150|Generating new keys
2023-02-04 22:05:20.889|I|config.py:154|bridge_public_key: -deleted-
2023-02-04 22:05:20.889|I|config.py:155|bridge_private_key: -deleted-
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/./__main__.py", line 66, in <module>
    nuki_manager, data = init_config(config_file, addon_config_file)
  File "/opt/./config.py", line 98, in init_config
    if len(nuki_devices) > 1:
TypeError: object of type 'NoneType' has no len()
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by cirolaferrara** [comment]
Same here

**Comment by Niconaco** [comment]
hi, I have the same problem, did you solve it?

**Comment by HPWicked** [comment]
> hi, I have the same problem, did you solve it?

@Niconaco 

I disabled the internal Raspberry Bluetooth port in the /boot/config.txt file and put the Raspberry super close (1 meter) to the Smartlock. 

It looks like that during the pairing mode the Bluetooth range is not the same as the usual one. 

My Raspberry with an external dongle (Maxuni Bluetooth USB Adapter Dongle 5.1) is roughly 8 meters away from the look and has -76 dBm locking the door works but the pairing would not.

**Comment by Niconacoo** [comment]
@HPWicked hello, i solved it! only later when I integrate it with nuki lock it integrates but then it gives me this error: homeassistant.config_entries
Source: helpers/network.py:206
First occurred: 20:09:23 (1 occurrences)
Last logged: 20:09:23

Error setting up entry serratura entrata for nuki_ng
Traceback (most recent call last):
File “/usr/src/homeassistant/homeassistant/config_entries.py”, line 383, in async_setup
result = await component.async_setup_entry(hass, self)
File “/config/custom_components/nuki_ng/init.py”, line 25, in async_setup_entry
coordinator = NukiCoordinator(hass, entry, data)
File “/config/custom_components/nuki_ng/nuki.py”, line 344, in init
url = config.get(“hass_url”, get_url(hass))
File “/usr/src/homeassistant/homeassistant/helpers/network.py”, line 167, in get_url
request_host = _get_request_host()
File “/usr/src/homeassistant/homeassistant/helpers/network.py”, line 206, in _get_request_host
raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

 could you help me please? in the other forum they don't answer. thanks
