### ISSUE TITLE
Problem - interface "org.bluez.Adapter1" doesn't exist

### ISSUE THREAD

**Issue by xBodziu** [regevbr/RaspiNukiBridge#15]
Hello,
I want to use this - https://github.com/regevbr/RaspiNukiBridge, I have configured Nuki Smart Lock 3.0 Pro and I want to integrate with HA. I have server on HP T620 (proxmox).

LOGS:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Nuki Bridge
 Virtual Nuki Bridge to use instead of the physical device
-----------------------------------------------------------
 Add-on version: 0.0.23
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.2.5
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2023-02-24 14:41:31.887|I|config.py:144|Access Token: XXX
2023-02-24 14:41:31.888|I|config.py:145|app_id: XXX
2023-02-24 14:41:31.889|I|config.py:150|Generating new keys
2023-02-24 14:41:31.890|I|config.py:154|bridge_public_key: XXX
2023-02-24 14:41:31.890|I|config.py:155|bridge_private_key: XXX
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/./__main__.py", line 66, in <module>
    nuki_manager, data = init_config(config_file, addon_config_file)
  File "/opt/./config.py", line 97, in init_config
    nuki_devices = find_ble_device('Nuki_.*', logger)
  File "/opt/./scan_ble.py", line 31, in find_ble_device
    result = loop.run_until_complete(_device_mac_address(regex, logger, only_one))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/./scan_ble.py", line 19, in _device_mac_address
    async with BleakScanner() as scanner:
  File "/usr/lib/python3.9/site-packages/bleak/backends/scanner.py", line 95, in __aenter__
    await self.start()
  File "/usr/lib/python3.9/site-packages/bleak/backends/bluezdbus/scanner.py", line 155, in start
    assert_reply(reply)
  File "/usr/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by fluxtv** [comment]
do you have a bluetooth adapter connected to your HA?
