### ISSUE TITLE
Pairing does not work

### ISSUE THREAD

**Issue by alekdebski** [regevbr/RaspiNukiBridge#17]
@regevbr  Regardless if I have nuki 1m from RBPi, the HA pairing never works. It detects nuki but then throws:

`Task exception was never retrieved
future: <Task finished name='Task-16' coro=<NukiManager._detected_ibeacon() done, defined at /opt/./nuki.py:212> exception=TypeError("unsupported operand type(s) for +: 'NoneType' and 'bytes'")>
Traceback (most recent call last):
  File "/opt/./nuki.py", line 238, in _detected_ibeacon
    await nuki.update_state()
  File "/opt/./nuki.py", line 704, in update_state
    cmd = self._encrypt_command(NukiCommand.REQUEST_DATA.value, payload)
  File "/opt/./nuki.py", line 393, in _encrypt_command
    unencrypted = self.auth_id + self._prepare_command(cmd_code, payload)[:-2]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'bytes'
2023-03-13 21:44:27.169|I|nuki.py:258|No more tasks - cleaning up`

**Comment by regevbr** [comment]
Hi @alekdebski I have stopped maintaining this repo as it is not stable. I recommend moving to the very reliable https://github.com/technyon/nuki_hub project (which requires a cheap 3 USD esp board)

**Comment by regevbr** [comment]
A PR is more than welcome though :-)
