### ISSUE TITLE
won't start on pi

### ISSUE THREAD

**Issue by t0bse** [regevbr/RaspiNukiBridge#5]
```
pi@raspberrypi:~/RaspiNukiBridge/nuki_bridge $ sudo python .
2022-10-01 20:58:25.660|I|config.py:144|Access Token: 55bd21d8175095xxx9dab117faa8f41bc372c6c
2022-10-01 20:58:25.660|I|config.py:145|app_id: 2180831399
2022-10-01 20:58:25.662|I|config.py:150|Generating new keys
2022-10-01 20:58:25.663|I|config.py:154|bridge_public_key: 6e12c0a847b5f0b4a8688xxx93ad02bbf7e7236110fb6f
2022-10-01 20:58:25.663|I|config.py:155|bridge_private_key: 24ae3a564e0bxxx7d4073c6bd9f3aff6d6f109a986
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 66, in <module>
    nuki_manager, data = init_config(config_file, addon_config_file)
  File "./config.py", line 89, in init_config
    if global_retry:
NameError: name 'global_retry' is not defined
```

**Comment by TBSniller** [comment]
@t0bse was struggeling with this too. Seems like you will have to manually define config path location and create those files.

Try the following:
```
# Go to python-files in your clone
cd /YOURPATH/RaspiNukiBridge/nuki_bridge

# Create data dir
mkdir -p data

# Generate config files
python3 . --generate-config > data/nuki.yaml
echo '{
        "retry": 5,
        "connection_timeout": 30,
        "command_timeout": 30
}' > data/options.json  # Don't know how good or bad this options are

# Edit nuki.yaml as it may contain log output in first lines, so remove them
nano data/nuki.yaml

# Edit consts.py to new file paths
echo "CONF_FILE_NAME = 'nuki.yaml'
ADDON_CONF_FILE_NAME = 'options.json'
DATA_PATH = '/YOURPATH/nuki_bridge/data'" > consts.py
```

**Comment by justcop** [comment]
Any ideas on the fix if I'm running this as a homeassistant addon? Its all run in a docker package so I'm not sure what "YOURPATH" would be.
