### ISSUE TITLE
NameError: name 'global_retry' is not defined

### ISSUE THREAD

**Issue by chrispazz** [regevbr/RaspiNukiBridge#8]
I get this error when executing:

python .

to pair.
Pairing with original Nuki project from dauden1184 is working ok.

Thank you

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/RaspiNukiBridge/nuki_bridge/./__main__.py", line 66, in <module>
    nuki_manager, data = init_config(config_file, addon_config_file)
  File "/home/pi/RaspiNukiBridge/nuki_bridge/./config.py", line 66, in init_config
    if global_retry:
NameError: name 'global_retry' is not defined
```

**Comment by Arn0uDz** [comment]
Getting the same error message.

Did you happen to solve this?

**Comment by sciorty** [comment]
same here

**Comment by vidalpascual** [comment]
Same error here. Any solution?
